### ISSUE TITLE
Running minimal.cc

### ISSUE THREAD

**Issue by DylanSnyder31** [milinddeore/TfLite-Standalone-build-Linux-MacOS#1]
I don't think this is a problem with this repo, per say, I think this is a problem with me. No matter how I build Tensorflow Lite I get the error:

./tensorflow/lite/interpreter.h:26:10: fatal error: 'tensorflow/lite/allocation.h'
      file not found
#include "tensorflow/lite/allocation.h"

when I try to import tensorflow/lite/interpreter.h. I'm pretty sure this is a problem with my path-setup but I don't know.

**Comment by milinddeore** [comment]
That means compiler is able to find `./tensorflow/lite/interpreter.h` but not able to find `tensorflow/lite/allocation.h`. Can you manually check is this file exist in the `./tensorflow/lite`?

Because i can see that `tensorflow/lite/allocation.h` is present in this repository unless you built tensorflow yourself and forgot to copy the file. Can you please check it?

**Comment by DylanSnyder31** [comment]
Yes, the file is there.

**Comment by milinddeore** [comment]
and i believe that you `-I` option is also correctly set to `tensorflow/lite/` as mentioned in the Makefile? 

Can you also check if your `PATH` is set properly? It must have `.` like following:
`export PATH=$PATH:.`

Apologies if you already tried it, i just thinking wild :)

**Comment by DylanSnyder31** [comment]
Ya I already had all that working. I got it working, though. I think it had something to do with my system and my g++ because I cleared out a lot of duplicate filed in /usr/local and it seemed to do the trick. Thanks for the help, however!
